use chat_rp_db;

INSERT INTO `designers` VALUES (1, 'いらすとや', NOW(), NOW());
INSERT INTO `designers` VALUES (14, 'HS_29', NOW(), NOW());

INSERT INTO `charachips` VALUES (1, '人狼BBS', 1, 'https://www.irasutoya.com/', true, NOW(), NOW());
INSERT INTO `charachips` VALUES (16, '御常紀学園', 14, 'https://hs29comet.com/chara-chip/otoko/', TRUE, NOW(), NOW());

INSERT INTO `charas`  VALUES (1, '楽天家 ゲルト', 1, 50, 77, now(), now());
INSERT INTO `charas`  VALUES (2, '村長 ヴァルター', 1, 50, 77, now(), now());
INSERT INTO `charas`  VALUES (3, '老人 モーリッツ', 1, 50, 77, now(), now());
INSERT INTO `charas`  VALUES (4, '神父 ジムゾン', 1, 50, 77, now(), now());
INSERT INTO `charas`  VALUES (5, '木こり トーマス', 1, 50, 77, now(), now());
INSERT INTO `charas`  VALUES (6, '旅人 ニコラス', 1, 50, 77, now(), now());
INSERT INTO `charas`  VALUES (7, 'ならず者 ディーター', 1, 50, 77, now(), now());
INSERT INTO `charas`  VALUES (8, '少年 ペーター', 1, 50, 77, now(), now());
INSERT INTO `charas`  VALUES (9, '少女 リーザ', 1, 50, 77, now(), now());
INSERT INTO `charas`  VALUES (10, '行商人 アルビン', 1, 50, 77, now(), now());
INSERT INTO `charas`  VALUES (11, '羊飼い カタリナ', 1, 50, 77, now(), now());
INSERT INTO `charas`  VALUES (12, 'パン屋 オットー', 1, 50, 77, now(), now());
INSERT INTO `charas`  VALUES (13, '青年 ヨアヒム', 1, 50, 77, now(), now());
INSERT INTO `charas`  VALUES (14, '村娘 パメラ', 1, 50, 77, now(), now());
INSERT INTO `charas`  VALUES (15, '農夫 ヤコブ', 1, 50, 77, now(), now());
INSERT INTO `charas`  VALUES (16, '宿屋の女主人 レジーナ', 1, 50, 77, now(), now());
INSERT INTO `charas`  VALUES (17, 'シスター フリーデル', 1, 50, 77, now(), now());
INSERT INTO `charas`  VALUES (18, '仕立て屋 エルナ', 1, 50, 77, now(), now());
INSERT INTO `charas`  VALUES (19, '司書 クララ', 1, 50, 77, now(), now());
INSERT INTO `charas`  VALUES (20, '負傷兵 シモン', 1, 50, 77, now(), now());

INSERT INTO `charas` VALUES (1301, '猫ノ ぬい', 16, 45, 65, NOW(), NOW());
INSERT INTO `charas` VALUES (1302, '犬井 ぐる', 16, 45, 65, NOW(), NOW());
INSERT INTO `charas` VALUES (1303, '有楽 澪', 16, 45, 65, NOW(), NOW());
INSERT INTO `charas` VALUES (1304, '迷彩リョウ', 16, 45, 65, NOW(), NOW());
INSERT INTO `charas` VALUES (1305, '黒塚 彰人', 16, 45, 65, NOW(), NOW());
INSERT INTO `charas` VALUES (1306, '仲山 健太', 16, 45, 65, NOW(), NOW());
INSERT INTO `charas` VALUES (1307, '朝倉 弘', 16, 45, 65, NOW(), NOW());
INSERT INTO `charas` VALUES (1308, '愛田 ノドカ', 16, 45, 65, NOW(), NOW());
INSERT INTO `charas` VALUES (1309, '夕月和', 16, 45, 65, NOW(), NOW());
INSERT INTO `charas` VALUES (1310, '普川 尚久', 16, 45, 65, NOW(), NOW());
INSERT INTO `charas` VALUES (1311, '鏡沼 創', 16, 45, 65, NOW(), NOW());
INSERT INTO `charas` VALUES (1312, '榊 潤', 16, 45, 65, NOW(), NOW());
INSERT INTO `charas` VALUES (1313, '夢乃華', 16, 45, 65, NOW(), NOW());
INSERT INTO `charas` VALUES (1314, '日方 陽介', 16, 45, 65, NOW(), NOW());
INSERT INTO `charas` VALUES (1315, '素崎真斗', 16, 45, 65, NOW(), NOW());
INSERT INTO `charas` VALUES (1316, '蒼生 悠馬', 16, 45, 65, NOW(), NOW());
INSERT INTO `charas` VALUES (1317, '宇奈うな', 16, 45, 65, NOW(), NOW());
INSERT INTO `charas` VALUES (1318, '貴戸 高志', 16, 45, 65, NOW(), NOW());
INSERT INTO `charas` VALUES (1319, '闇谷暁', 16, 45, 65, NOW(), NOW());
INSERT INTO `charas` VALUES (1320, '異邦アンディ', 16, 45, 65, NOW(), NOW());
INSERT INTO `charas` VALUES (1321, '清瀬 遥', 16, 45, 65, NOW(), NOW());
INSERT INTO `charas` VALUES (1322, '蛇眼 リドウ', 16, 45, 65, NOW(), NOW());
INSERT INTO `charas` VALUES (1323, '覆下聡太郎', 16, 45, 65, NOW(), NOW());
INSERT INTO `charas` VALUES (1324, '豊橋 優弥', 16, 45, 65, NOW(), NOW());
INSERT INTO `charas` VALUES (1325, '宮間 マオ', 16, 45, 65, NOW(), NOW());
INSERT INTO `charas` VALUES (1326, '神谷 永太', 16, 45, 65, NOW(), NOW());
INSERT INTO `charas` VALUES (1327, '南波 靖史', 16, 45, 65, NOW(), NOW());
INSERT INTO `charas` VALUES (1328, '遊城 憲義', 16, 45, 65, NOW(), NOW());
INSERT INTO `charas` VALUES (1329, '白入 熊', 16, 45, 65, NOW(), NOW());
INSERT INTO `charas` VALUES (1330, '朱鷺 慶人', 16, 45, 65, NOW(), NOW());
INSERT INTO `charas` VALUES (1331, '透 静', 16, 45, 65, NOW(), NOW());
INSERT INTO `charas` VALUES (1332, '天羽 望', 16, 45, 65, NOW(), NOW());
INSERT INTO `charas` VALUES (1445, '市川 夢助', 16, 45, 65, NOW(), NOW());
INSERT INTO `charas` VALUES (1446, '千葉 郁也', 16, 45, 65, NOW(), NOW());
INSERT INTO `charas` VALUES (1703, '絵野 美輝', 16, 45, 65, NOW(), NOW());
INSERT INTO `charas` VALUES (1704, '天野川 空', 16, 45, 65, NOW(), NOW());
INSERT INTO `charas` VALUES (1705, '上葛 掃司', 16, 45, 65, NOW(), NOW());
INSERT INTO `charas` VALUES (1706, '川瀬 礼人', 16, 45, 65, NOW(), NOW());
INSERT INTO `charas` VALUES (1707, '呉ノ 藍', 16, 45, 65, NOW(), NOW());
INSERT INTO `charas` VALUES (1708, '白百合 いちか', 16, 45, 65, NOW(), NOW());
INSERT INTO `charas` VALUES (1709, '若草 楓', 16, 45, 65, NOW(), NOW());
INSERT INTO `charas` VALUES (1710, '光司 一誠', 16, 45, 65, NOW(), NOW());
INSERT INTO `charas` VALUES (1711, '冬風 瑞希', 16, 45, 65, NOW(), NOW());
INSERT INTO `charas` VALUES (1712, '古屋 秋', 16, 45, 65, NOW(), NOW());
INSERT INTO `charas` VALUES (1713, '転開 実', 16, 45, 65, NOW(), NOW());
INSERT INTO `charas` VALUES (1714, '裏部 恭邦', 16, 45, 65, NOW(), NOW());
INSERT INTO `charas` VALUES (1715, '素崎 理仁', 16, 45, 65, NOW(), NOW());
INSERT INTO `charas` VALUES (1716, '坂澤 小次郎', 16, 45, 65, NOW(), NOW());
INSERT INTO `charas` VALUES (1717, '春浦 新一', 16, 45, 65, NOW(), NOW());
INSERT INTO `charas` VALUES (1718, '夏目 沙芽', 16, 45, 65, NOW(), NOW());
INSERT INTO `charas` VALUES (1719, '影半 郁明', 16, 45, 65, NOW(), NOW());
INSERT INTO `charas` VALUES (1720, '隠岐 シヅク', 16, 45, 65, NOW(), NOW());
INSERT INTO `charas` VALUES (1721, '狸山 ぽん', 16, 45, 65, NOW(), NOW());
INSERT INTO `charas` VALUES (1722, '切裂 刃', 16, 45, 65, NOW(), NOW());
INSERT INTO `charas` VALUES (2868, '月見 シトギ', 16, 45, 65, NOW(), NOW());
INSERT INTO `charas` VALUES (2869, '飴玉 ルリ', 16, 45, 65, NOW(), NOW());
INSERT INTO `charas` VALUES (3171, '堤下 相午', 16, 45, 65, NOW(), NOW());
INSERT INTO `charas` VALUES (3172, '真木 智行', 16, 45, 65, NOW(), NOW());
INSERT INTO `charas` VALUES (3173, '雷伝 樂', 16, 45, 65, NOW(), NOW());
INSERT INTO `charas` VALUES (3174, '炎道 姿', 16, 45, 65, NOW(), NOW());
INSERT INTO `charas` VALUES (3175, '軽梅 乃々里', 16, 45, 65, NOW(), NOW());
INSERT INTO `charas` VALUES (3176, '闘真 拳十', 16, 45, 65, NOW(), NOW());
INSERT INTO `charas` VALUES (3177, '追石 壱途', 16, 45, 65, NOW(), NOW());
INSERT INTO `charas` VALUES (3178, '未来 翼', 16, 45, 65, NOW(), NOW());
INSERT INTO `charas` VALUES (3179, '赤 浩龍', 16, 45, 65, NOW(), NOW());
INSERT INTO `charas` VALUES (3180, '屑野 極見', 16, 45, 65, NOW(), NOW());
INSERT INTO `charas` VALUES (3181, '長杉 明日陽', 16, 45, 65, NOW(), NOW());
INSERT INTO `charas` VALUES (3182, '機動 ロイ', 16, 45, 65, NOW(), NOW());
INSERT INTO `charas` VALUES (3183, '織多 史也', 16, 45, 65, NOW(), NOW());
INSERT INTO `charas` VALUES (3184, '好沢 世治', 16, 45, 65, NOW(), NOW());
INSERT INTO `charas` VALUES (3185, '箱紙らって', 16, 45, 65, NOW(), NOW());
INSERT INTO `charas` VALUES (3186, '煌希 ラキ', 16, 45, 65, NOW(), NOW());
INSERT INTO `charas` VALUES (3187, '輝金 昴流', 16, 45, 65, NOW(), NOW());
INSERT INTO `charas` VALUES (3188, '志渡 駿', 16, 45, 65, NOW(), NOW());
INSERT INTO `charas` VALUES (3189, '病居 カコイ', 16, 45, 65, NOW(), NOW());
INSERT INTO `charas` VALUES (3190, '薬師院 メリア', 16, 45, 65, NOW(), NOW());

INSERT INTO `chara_images` VALUES (1, 1, 'NORMAL', 'https://wolfort.net/wolf-mansion/app/images/geruto.png', NOW(), NOW());
INSERT INTO `chara_images` VALUES (2, 2, 'NORMAL', 'https://wolfort.net/wolf-mansion/app/images/varuta.png', NOW(), NOW());
INSERT INTO `chara_images` VALUES (3, 3, 'NORMAL', 'https://wolfort.net/wolf-mansion/app/images/moritu.png', NOW(), NOW());
INSERT INTO `chara_images` VALUES (4, 4, 'NORMAL', 'https://wolfort.net/wolf-mansion/app/images/jimuzon.png', NOW(), NOW());
INSERT INTO `chara_images` VALUES (5, 5, 'NORMAL', 'https://wolfort.net/wolf-mansion/app/images/tomasu.png', NOW(), NOW());
INSERT INTO `chara_images` VALUES (6, 6, 'NORMAL', 'https://wolfort.net/wolf-mansion/app/images/nikorasu.png', NOW(), NOW());
INSERT INTO `chara_images` VALUES (7, 7, 'NORMAL', 'https://wolfort.net/wolf-mansion/app/images/dhita.png', NOW(), NOW());
INSERT INTO `chara_images` VALUES (8, 8, 'NORMAL', 'https://wolfort.net/wolf-mansion/app/images/peta.png', NOW(), NOW());
INSERT INTO `chara_images` VALUES (9, 9, 'NORMAL', 'https://wolfort.net/wolf-mansion/app/images/riza.png', NOW(), NOW());
INSERT INTO `chara_images` VALUES (10, 10, 'NORMAL', 'https://wolfort.net/wolf-mansion/app/images/arubin.png', NOW(), NOW());
INSERT INTO `chara_images` VALUES (11, 11, 'NORMAL', 'https://wolfort.net/wolf-mansion/app/images/katarina.png', NOW(), NOW());
INSERT INTO `chara_images` VALUES (12, 12, 'NORMAL', 'https://wolfort.net/wolf-mansion/app/images/otto.png', NOW(), NOW());
INSERT INTO `chara_images` VALUES (13, 13, 'NORMAL', 'https://wolfort.net/wolf-mansion/app/images/yoahimu.png', NOW(), NOW());
INSERT INTO `chara_images` VALUES (14, 14, 'NORMAL', 'https://wolfort.net/wolf-mansion/app/images/pamera.png', NOW(), NOW());
INSERT INTO `chara_images` VALUES (15, 15, 'NORMAL', 'https://wolfort.net/wolf-mansion/app/images/yakobu.png', NOW(), NOW());
INSERT INTO `chara_images` VALUES (16, 16, 'NORMAL', 'https://wolfort.net/wolf-mansion/app/images/rejina.png', NOW(), NOW());
INSERT INTO `chara_images` VALUES (17, 17, 'NORMAL', 'https://wolfort.net/wolf-mansion/app/images/furideru.png', NOW(), NOW());
INSERT INTO `chara_images` VALUES (18, 18, 'NORMAL', 'https://wolfort.net/wolf-mansion/app/images/eruna.png', NOW(), NOW());
INSERT INTO `chara_images` VALUES (19, 19, 'NORMAL', 'https://wolfort.net/wolf-mansion/app/images/kurara.png', NOW(), NOW());
INSERT INTO `chara_images` VALUES (20, 20, 'NORMAL', 'https://wolfort.net/wolf-mansion/app/images/shimon.png', NOW(), NOW());

INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1301, 'GRAVE', 'https://wolfort.net/wmansion/16/001_b.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1301, 'LOVER', 'https://wolfort.net/wmansion/16/001_p.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1301, 'NORMAL', 'https://wolfort.net/wmansion/16/001_n.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1301, 'WEREWOLF', 'https://wolfort.net/wmansion/16/001_r.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1302, 'GRAVE', 'https://wolfort.net/wmansion/16/002_b.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1302, 'LOVER', 'https://wolfort.net/wmansion/16/002_p.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1302, 'NORMAL', 'https://wolfort.net/wmansion/16/002_n.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1302, 'WEREWOLF', 'https://wolfort.net/wmansion/16/002_r.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1303, 'GRAVE', 'https://wolfort.net/wmansion/16/003_b.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1303, 'LOVER', 'https://wolfort.net/wmansion/16/003_p.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1303, 'NORMAL', 'https://wolfort.net/wmansion/16/003_n.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1303, 'WEREWOLF', 'https://wolfort.net/wmansion/16/003_r.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1304, 'GRAVE', 'https://wolfort.net/wmansion/16/004_b.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1304, 'LOVER', 'https://wolfort.net/wmansion/16/004_p.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1304, 'NORMAL', 'https://wolfort.net/wmansion/16/004_n.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1304, 'WEREWOLF', 'https://wolfort.net/wmansion/16/004_r.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1305, 'GRAVE', 'https://wolfort.net/wmansion/16/005_b.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1305, 'LOVER', 'https://wolfort.net/wmansion/16/005_p.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1305, 'NORMAL', 'https://wolfort.net/wmansion/16/005_n.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1305, 'WEREWOLF', 'https://wolfort.net/wmansion/16/005_r.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1306, 'GRAVE', 'https://wolfort.net/wmansion/16/006_b.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1306, 'LOVER', 'https://wolfort.net/wmansion/16/006_p.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1306, 'NORMAL', 'https://wolfort.net/wmansion/16/006_n.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1306, 'WEREWOLF', 'https://wolfort.net/wmansion/16/006_r.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1307, 'GRAVE', 'https://wolfort.net/wmansion/16/007_b.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1307, 'LOVER', 'https://wolfort.net/wmansion/16/007_p.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1307, 'NORMAL', 'https://wolfort.net/wmansion/16/007_n.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1307, 'WEREWOLF', 'https://wolfort.net/wmansion/16/007_r.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1308, 'GRAVE', 'https://wolfort.net/wmansion/16/008_b.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1308, 'LOVER', 'https://wolfort.net/wmansion/16/008_p.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1308, 'NORMAL', 'https://wolfort.net/wmansion/16/008_n.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1308, 'WEREWOLF', 'https://wolfort.net/wmansion/16/008_r.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1309, 'GRAVE', 'https://wolfort.net/wmansion/16/009_b.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1309, 'LOVER', 'https://wolfort.net/wmansion/16/009_p.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1309, 'NORMAL', 'https://wolfort.net/wmansion/16/009_n.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1309, 'WEREWOLF', 'https://wolfort.net/wmansion/16/009_r.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1310, 'GRAVE', 'https://wolfort.net/wmansion/16/010_b.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1310, 'LOVER', 'https://wolfort.net/wmansion/16/010_p.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1310, 'NORMAL', 'https://wolfort.net/wmansion/16/010_n.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1310, 'WEREWOLF', 'https://wolfort.net/wmansion/16/010_r.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1311, 'GRAVE', 'https://wolfort.net/wmansion/16/011_b.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1311, 'LOVER', 'https://wolfort.net/wmansion/16/011_p.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1311, 'NORMAL', 'https://wolfort.net/wmansion/16/011_n.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1311, 'WEREWOLF', 'https://wolfort.net/wmansion/16/011_r.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1312, 'GRAVE', 'https://wolfort.net/wmansion/16/012_b.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1312, 'LOVER', 'https://wolfort.net/wmansion/16/012_p.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1312, 'NORMAL', 'https://wolfort.net/wmansion/16/012_n.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1312, 'WEREWOLF', 'https://wolfort.net/wmansion/16/012_r.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1313, 'GRAVE', 'https://wolfort.net/wmansion/16/013_b.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1313, 'LOVER', 'https://wolfort.net/wmansion/16/013_p.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1313, 'NORMAL', 'https://wolfort.net/wmansion/16/013_n.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1313, 'WEREWOLF', 'https://wolfort.net/wmansion/16/013_r.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1314, 'GRAVE', 'https://wolfort.net/wmansion/16/014_b.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1314, 'LOVER', 'https://wolfort.net/wmansion/16/014_p.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1314, 'NORMAL', 'https://wolfort.net/wmansion/16/014_n.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1314, 'WEREWOLF', 'https://wolfort.net/wmansion/16/014_r.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1315, 'GRAVE', 'https://wolfort.net/wmansion/16/015_b.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1315, 'LOVER', 'https://wolfort.net/wmansion/16/015_p.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1315, 'NORMAL', 'https://wolfort.net/wmansion/16/015_n.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1315, 'WEREWOLF', 'https://wolfort.net/wmansion/16/015_r.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1316, 'GRAVE', 'https://wolfort.net/wmansion/16/016_b.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1316, 'LOVER', 'https://wolfort.net/wmansion/16/016_p.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1316, 'NORMAL', 'https://wolfort.net/wmansion/16/016_n.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1316, 'WEREWOLF', 'https://wolfort.net/wmansion/16/016_r.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1317, 'GRAVE', 'https://wolfort.net/wmansion/16/017_b.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1317, 'LOVER', 'https://wolfort.net/wmansion/16/017_p.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1317, 'NORMAL', 'https://wolfort.net/wmansion/16/017_n.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1317, 'WEREWOLF', 'https://wolfort.net/wmansion/16/017_r.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1318, 'GRAVE', 'https://wolfort.net/wmansion/16/018_b.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1318, 'LOVER', 'https://wolfort.net/wmansion/16/018_p.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1318, 'NORMAL', 'https://wolfort.net/wmansion/16/018_n.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1318, 'WEREWOLF', 'https://wolfort.net/wmansion/16/018_r.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1319, 'GRAVE', 'https://wolfort.net/wmansion/16/019_b.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1319, 'LOVER', 'https://wolfort.net/wmansion/16/019_p.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1319, 'NORMAL', 'https://wolfort.net/wmansion/16/019_n.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1319, 'WEREWOLF', 'https://wolfort.net/wmansion/16/019_r.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1320, 'GRAVE', 'https://wolfort.net/wmansion/16/020_b.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1320, 'LOVER', 'https://wolfort.net/wmansion/16/020_p.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1320, 'NORMAL', 'https://wolfort.net/wmansion/16/020_n.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1320, 'WEREWOLF', 'https://wolfort.net/wmansion/16/020_r.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1321, 'GRAVE', 'https://wolfort.net/wmansion/16/021_b.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1321, 'LOVER', 'https://wolfort.net/wmansion/16/021_p.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1321, 'NORMAL', 'https://wolfort.net/wmansion/16/021_n.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1321, 'WEREWOLF', 'https://wolfort.net/wmansion/16/021_r.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1322, 'GRAVE', 'https://wolfort.net/wmansion/16/022_b.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1322, 'LOVER', 'https://wolfort.net/wmansion/16/022_p.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1322, 'NORMAL', 'https://wolfort.net/wmansion/16/022_n.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1322, 'WEREWOLF', 'https://wolfort.net/wmansion/16/022_r.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1323, 'GRAVE', 'https://wolfort.net/wmansion/16/023_b.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1323, 'LOVER', 'https://wolfort.net/wmansion/16/023_p.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1323, 'NORMAL', 'https://wolfort.net/wmansion/16/023_n.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1323, 'WEREWOLF', 'https://wolfort.net/wmansion/16/023_r.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1324, 'GRAVE', 'https://wolfort.net/wmansion/16/024_b.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1324, 'LOVER', 'https://wolfort.net/wmansion/16/024_p.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1324, 'NORMAL', 'https://wolfort.net/wmansion/16/024_n.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1324, 'WEREWOLF', 'https://wolfort.net/wmansion/16/024_r.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1325, 'GRAVE', 'https://wolfort.net/wmansion/16/025_b.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1325, 'LOVER', 'https://wolfort.net/wmansion/16/025_p.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1325, 'NORMAL', 'https://wolfort.net/wmansion/16/025_n.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1325, 'WEREWOLF', 'https://wolfort.net/wmansion/16/025_r.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1326, 'GRAVE', 'https://wolfort.net/wmansion/16/026_b.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1326, 'LOVER', 'https://wolfort.net/wmansion/16/026_p.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1326, 'NORMAL', 'https://wolfort.net/wmansion/16/026_n.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1326, 'WEREWOLF', 'https://wolfort.net/wmansion/16/026_r.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1327, 'GRAVE', 'https://wolfort.net/wmansion/16/027_b.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1327, 'LOVER', 'https://wolfort.net/wmansion/16/027_p.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1327, 'NORMAL', 'https://wolfort.net/wmansion/16/027_n.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1327, 'WEREWOLF', 'https://wolfort.net/wmansion/16/027_r.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1328, 'GRAVE', 'https://wolfort.net/wmansion/16/028_b.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1328, 'LOVER', 'https://wolfort.net/wmansion/16/028_p.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1328, 'NORMAL', 'https://wolfort.net/wmansion/16/028_n.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1328, 'WEREWOLF', 'https://wolfort.net/wmansion/16/028_r.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1329, 'GRAVE', 'https://wolfort.net/wmansion/16/029_b.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1329, 'LOVER', 'https://wolfort.net/wmansion/16/029_p.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1329, 'NORMAL', 'https://wolfort.net/wmansion/16/029_n.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1329, 'WEREWOLF', 'https://wolfort.net/wmansion/16/029_r.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1330, 'GRAVE', 'https://wolfort.net/wmansion/16/030_b.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1330, 'LOVER', 'https://wolfort.net/wmansion/16/030_p.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1330, 'NORMAL', 'https://wolfort.net/wmansion/16/030_n.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1330, 'WEREWOLF', 'https://wolfort.net/wmansion/16/030_r.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1331, 'GRAVE', 'https://wolfort.net/wmansion/16/031_b.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1331, 'LOVER', 'https://wolfort.net/wmansion/16/031_p.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1331, 'NORMAL', 'https://wolfort.net/wmansion/16/031_n.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1331, 'WEREWOLF', 'https://wolfort.net/wmansion/16/031_r.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1332, 'GRAVE', 'https://wolfort.net/wmansion/16/032_b.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1332, 'LOVER', 'https://wolfort.net/wmansion/16/032_p.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1332, 'NORMAL', 'https://wolfort.net/wmansion/16/032_n.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1332, 'WEREWOLF', 'https://wolfort.net/wmansion/16/032_r.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1445, 'GRAVE', 'https://wolfort.net/wmansion/16/033_b.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1445, 'LOVER', 'https://wolfort.net/wmansion/16/033_p.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1445, 'NORMAL', 'https://wolfort.net/wmansion/16/033_n.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1445, 'WEREWOLF', 'https://wolfort.net/wmansion/16/033_r.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1446, 'GRAVE', 'https://wolfort.net/wmansion/16/034_b.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1446, 'LOVER', 'https://wolfort.net/wmansion/16/034_p.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1446, 'NORMAL', 'https://wolfort.net/wmansion/16/034_n.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1446, 'WEREWOLF', 'https://wolfort.net/wmansion/16/034_r.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1703, 'GRAVE', 'https://wolfort.net/wmansion/16/035_b.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1703, 'LOVER', 'https://wolfort.net/wmansion/16/035_p.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1703, 'NORMAL', 'https://wolfort.net/wmansion/16/035_n.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1703, 'WEREWOLF', 'https://wolfort.net/wmansion/16/035_r.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1704, 'GRAVE', 'https://wolfort.net/wmansion/16/036_b.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1704, 'LOVER', 'https://wolfort.net/wmansion/16/036_p.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1704, 'NORMAL', 'https://wolfort.net/wmansion/16/036_n.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1704, 'WEREWOLF', 'https://wolfort.net/wmansion/16/036_r.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1705, 'GRAVE', 'https://wolfort.net/wmansion/16/037_b.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1705, 'LOVER', 'https://wolfort.net/wmansion/16/037_p.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1705, 'NORMAL', 'https://wolfort.net/wmansion/16/037_n.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1705, 'WEREWOLF', 'https://wolfort.net/wmansion/16/037_r.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1706, 'GRAVE', 'https://wolfort.net/wmansion/16/038_b.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1706, 'LOVER', 'https://wolfort.net/wmansion/16/038_p.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1706, 'NORMAL', 'https://wolfort.net/wmansion/16/038_n.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1706, 'WEREWOLF', 'https://wolfort.net/wmansion/16/038_r.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1707, 'GRAVE', 'https://wolfort.net/wmansion/16/039_b.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1707, 'LOVER', 'https://wolfort.net/wmansion/16/039_p.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1707, 'NORMAL', 'https://wolfort.net/wmansion/16/039_n.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1707, 'WEREWOLF', 'https://wolfort.net/wmansion/16/039_r.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1708, 'GRAVE', 'https://wolfort.net/wmansion/16/040_b.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1708, 'LOVER', 'https://wolfort.net/wmansion/16/040_p.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1708, 'NORMAL', 'https://wolfort.net/wmansion/16/040_n.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1708, 'WEREWOLF', 'https://wolfort.net/wmansion/16/040_r.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1709, 'GRAVE', 'https://wolfort.net/wmansion/16/041_b.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1709, 'LOVER', 'https://wolfort.net/wmansion/16/041_p.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1709, 'NORMAL', 'https://wolfort.net/wmansion/16/041_n.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1709, 'WEREWOLF', 'https://wolfort.net/wmansion/16/041_r.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1710, 'GRAVE', 'https://wolfort.net/wmansion/16/042_b.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1710, 'LOVER', 'https://wolfort.net/wmansion/16/042_p.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1710, 'NORMAL', 'https://wolfort.net/wmansion/16/042_n.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1710, 'WEREWOLF', 'https://wolfort.net/wmansion/16/042_r.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1711, 'GRAVE', 'https://wolfort.net/wmansion/16/043_b.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1711, 'LOVER', 'https://wolfort.net/wmansion/16/043_p.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1711, 'NORMAL', 'https://wolfort.net/wmansion/16/043_n.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1711, 'WEREWOLF', 'https://wolfort.net/wmansion/16/043_r.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1712, 'GRAVE', 'https://wolfort.net/wmansion/16/044_b.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1712, 'LOVER', 'https://wolfort.net/wmansion/16/044_p.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1712, 'NORMAL', 'https://wolfort.net/wmansion/16/044_n.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1712, 'WEREWOLF', 'https://wolfort.net/wmansion/16/044_r.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1713, 'GRAVE', 'https://wolfort.net/wmansion/16/045_b.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1713, 'LOVER', 'https://wolfort.net/wmansion/16/045_p.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1713, 'NORMAL', 'https://wolfort.net/wmansion/16/045_n.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1713, 'WEREWOLF', 'https://wolfort.net/wmansion/16/045_r.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1714, 'GRAVE', 'https://wolfort.net/wmansion/16/046_b.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1714, 'LOVER', 'https://wolfort.net/wmansion/16/046_p.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1714, 'NORMAL', 'https://wolfort.net/wmansion/16/046_n.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1714, 'WEREWOLF', 'https://wolfort.net/wmansion/16/046_r.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1715, 'GRAVE', 'https://wolfort.net/wmansion/16/047_b.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1715, 'LOVER', 'https://wolfort.net/wmansion/16/047_p.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1715, 'NORMAL', 'https://wolfort.net/wmansion/16/047_n.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1715, 'WEREWOLF', 'https://wolfort.net/wmansion/16/047_r.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1716, 'GRAVE', 'https://wolfort.net/wmansion/16/048_b.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1716, 'LOVER', 'https://wolfort.net/wmansion/16/048_p.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1716, 'NORMAL', 'https://wolfort.net/wmansion/16/048_n.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1716, 'WEREWOLF', 'https://wolfort.net/wmansion/16/048_r.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1717, 'GRAVE', 'https://wolfort.net/wmansion/16/049_b.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1717, 'LOVER', 'https://wolfort.net/wmansion/16/049_p.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1717, 'NORMAL', 'https://wolfort.net/wmansion/16/049_n.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1717, 'WEREWOLF', 'https://wolfort.net/wmansion/16/049_r.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1718, 'GRAVE', 'https://wolfort.net/wmansion/16/050_b.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1718, 'LOVER', 'https://wolfort.net/wmansion/16/050_p.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1718, 'NORMAL', 'https://wolfort.net/wmansion/16/050_n.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1718, 'WEREWOLF', 'https://wolfort.net/wmansion/16/050_r.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1719, 'GRAVE', 'https://wolfort.net/wmansion/16/051_b.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1719, 'LOVER', 'https://wolfort.net/wmansion/16/051_p.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1719, 'NORMAL', 'https://wolfort.net/wmansion/16/051_n.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1719, 'WEREWOLF', 'https://wolfort.net/wmansion/16/051_r.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1720, 'GRAVE', 'https://wolfort.net/wmansion/16/052_b.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1720, 'LOVER', 'https://wolfort.net/wmansion/16/052_p.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1720, 'NORMAL', 'https://wolfort.net/wmansion/16/052_n.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1720, 'WEREWOLF', 'https://wolfort.net/wmansion/16/052_r.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1721, 'GRAVE', 'https://wolfort.net/wmansion/16/053_b.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1721, 'LOVER', 'https://wolfort.net/wmansion/16/053_p.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1721, 'NORMAL', 'https://wolfort.net/wmansion/16/053_n.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1721, 'WEREWOLF', 'https://wolfort.net/wmansion/16/053_r.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1722, 'GRAVE', 'https://wolfort.net/wmansion/16/054_b.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1722, 'LOVER', 'https://wolfort.net/wmansion/16/054_p.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1722, 'NORMAL', 'https://wolfort.net/wmansion/16/054_n.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 1722, 'WEREWOLF', 'https://wolfort.net/wmansion/16/054_r.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 2868, 'GRAVE', 'https://wolfort.net/wmansion/16/055_b.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 2868, 'LOVER', 'https://wolfort.net/wmansion/16/055_p.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 2868, 'NORMAL', 'https://wolfort.net/wmansion/16/055_n.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 2868, 'WEREWOLF', 'https://wolfort.net/wmansion/16/055_r.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 2869, 'GRAVE', 'https://wolfort.net/wmansion/16/056_b.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 2869, 'LOVER', 'https://wolfort.net/wmansion/16/056_p.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 2869, 'NORMAL', 'https://wolfort.net/wmansion/16/056_n.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 2869, 'WEREWOLF', 'https://wolfort.net/wmansion/16/056_r.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 3171, 'GRAVE', 'https://wolfort.net/wmansion/16/057_b.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 3171, 'LOVER', 'https://wolfort.net/wmansion/16/057_p.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 3171, 'NORMAL', 'https://wolfort.net/wmansion/16/057_n.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 3171, 'WEREWOLF', 'https://wolfort.net/wmansion/16/057_r.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 3172, 'GRAVE', 'https://wolfort.net/wmansion/16/058_b.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 3172, 'LOVER', 'https://wolfort.net/wmansion/16/058_p.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 3172, 'NORMAL', 'https://wolfort.net/wmansion/16/058_n.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 3172, 'WEREWOLF', 'https://wolfort.net/wmansion/16/058_r.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 3173, 'GRAVE', 'https://wolfort.net/wmansion/16/059_b.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 3173, 'LOVER', 'https://wolfort.net/wmansion/16/059_p.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 3173, 'NORMAL', 'https://wolfort.net/wmansion/16/059_n.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 3173, 'WEREWOLF', 'https://wolfort.net/wmansion/16/059_r.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 3174, 'GRAVE', 'https://wolfort.net/wmansion/16/060_b.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 3174, 'LOVER', 'https://wolfort.net/wmansion/16/060_p.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 3174, 'NORMAL', 'https://wolfort.net/wmansion/16/060_n.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 3174, 'WEREWOLF', 'https://wolfort.net/wmansion/16/060_r.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 3175, 'GRAVE', 'https://wolfort.net/wmansion/16/061_b.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 3175, 'LOVER', 'https://wolfort.net/wmansion/16/061_p.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 3175, 'NORMAL', 'https://wolfort.net/wmansion/16/061_n.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 3175, 'WEREWOLF', 'https://wolfort.net/wmansion/16/061_r.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 3176, 'GRAVE', 'https://wolfort.net/wmansion/16/062_b.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 3176, 'LOVER', 'https://wolfort.net/wmansion/16/062_p.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 3176, 'NORMAL', 'https://wolfort.net/wmansion/16/062_n.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 3176, 'WEREWOLF', 'https://wolfort.net/wmansion/16/062_r.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 3177, 'GRAVE', 'https://wolfort.net/wmansion/16/063_b.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 3177, 'LOVER', 'https://wolfort.net/wmansion/16/063_p.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 3177, 'NORMAL', 'https://wolfort.net/wmansion/16/063_n.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 3177, 'WEREWOLF', 'https://wolfort.net/wmansion/16/063_r.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 3178, 'GRAVE', 'https://wolfort.net/wmansion/16/064_b.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 3178, 'LOVER', 'https://wolfort.net/wmansion/16/064_p.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 3178, 'NORMAL', 'https://wolfort.net/wmansion/16/064_n.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 3178, 'WEREWOLF', 'https://wolfort.net/wmansion/16/064_r.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 3179, 'GRAVE', 'https://wolfort.net/wmansion/16/065_b.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 3179, 'LOVER', 'https://wolfort.net/wmansion/16/065_p.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 3179, 'NORMAL', 'https://wolfort.net/wmansion/16/065_n.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 3179, 'WEREWOLF', 'https://wolfort.net/wmansion/16/065_r.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 3180, 'GRAVE', 'https://wolfort.net/wmansion/16/066_b.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 3180, 'LOVER', 'https://wolfort.net/wmansion/16/066_p.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 3180, 'NORMAL', 'https://wolfort.net/wmansion/16/066_n.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 3180, 'WEREWOLF', 'https://wolfort.net/wmansion/16/066_r.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 3181, 'GRAVE', 'https://wolfort.net/wmansion/16/067_b.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 3181, 'LOVER', 'https://wolfort.net/wmansion/16/067_p.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 3181, 'NORMAL', 'https://wolfort.net/wmansion/16/067_n.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 3181, 'WEREWOLF', 'https://wolfort.net/wmansion/16/067_r.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 3182, 'GRAVE', 'https://wolfort.net/wmansion/16/068_b.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 3182, 'LOVER', 'https://wolfort.net/wmansion/16/068_p.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 3182, 'NORMAL', 'https://wolfort.net/wmansion/16/068_n.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 3182, 'WEREWOLF', 'https://wolfort.net/wmansion/16/068_r.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 3183, 'GRAVE', 'https://wolfort.net/wmansion/16/069_b.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 3183, 'LOVER', 'https://wolfort.net/wmansion/16/069_p.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 3183, 'NORMAL', 'https://wolfort.net/wmansion/16/069_n.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 3183, 'WEREWOLF', 'https://wolfort.net/wmansion/16/069_r.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 3184, 'GRAVE', 'https://wolfort.net/wmansion/16/070_b.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 3184, 'LOVER', 'https://wolfort.net/wmansion/16/070_p.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 3184, 'NORMAL', 'https://wolfort.net/wmansion/16/070_n.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 3184, 'WEREWOLF', 'https://wolfort.net/wmansion/16/070_r.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 3185, 'GRAVE', 'https://wolfort.net/wmansion/16/071_b.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 3185, 'LOVER', 'https://wolfort.net/wmansion/16/071_p.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 3185, 'NORMAL', 'https://wolfort.net/wmansion/16/071_n.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 3185, 'WEREWOLF', 'https://wolfort.net/wmansion/16/071_r.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 3186, 'GRAVE', 'https://wolfort.net/wmansion/16/072_b.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 3186, 'LOVER', 'https://wolfort.net/wmansion/16/072_p.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 3186, 'NORMAL', 'https://wolfort.net/wmansion/16/072_n.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 3186, 'WEREWOLF', 'https://wolfort.net/wmansion/16/072_r.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 3187, 'GRAVE', 'https://wolfort.net/wmansion/16/073_b.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 3187, 'LOVER', 'https://wolfort.net/wmansion/16/073_p.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 3187, 'NORMAL', 'https://wolfort.net/wmansion/16/073_n.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 3187, 'WEREWOLF', 'https://wolfort.net/wmansion/16/073_r.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 3188, 'GRAVE', 'https://wolfort.net/wmansion/16/074_b.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 3188, 'LOVER', 'https://wolfort.net/wmansion/16/074_p.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 3188, 'NORMAL', 'https://wolfort.net/wmansion/16/074_n.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 3188, 'WEREWOLF', 'https://wolfort.net/wmansion/16/074_r.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 3189, 'GRAVE', 'https://wolfort.net/wmansion/16/075_b.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 3189, 'LOVER', 'https://wolfort.net/wmansion/16/075_p.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 3189, 'NORMAL', 'https://wolfort.net/wmansion/16/075_n.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 3189, 'WEREWOLF', 'https://wolfort.net/wmansion/16/075_r.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 3190, 'GRAVE', 'https://wolfort.net/wmansion/16/076_b.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 3190, 'LOVER', 'https://wolfort.net/wmansion/16/076_p.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 3190, 'NORMAL', 'https://wolfort.net/wmansion/16/076_n.png', NOW(), NOW());
INSERT INTO `CHARA_IMAGES` VALUES (NULL, 3190, 'WEREWOLF', 'https://wolfort.net/wmansion/16/076_r.png', NOW(), NOW());
