name: delivery frontend

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "frontend/**"
      - ".github/workflows/deploy_frontend.yml"

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
      packages: write
    env:
      IMAGE_NAME: chat-role-play-frontend
    steps:
      - name: clone repository
        uses: actions/checkout@v4

      - name: build
        run: >
          docker build
          -t ghcr.io/h-orito/${{ env.IMAGE_NAME }}:latest ./frontend
          --build-arg AUTH0_DOMAIN=${{ secrets.AUTH0_DOMAIN }}
          --build-arg AUTH0_CLIENT_ID=${{ secrets.AUTH0_CLIENT_ID }}
          --build-arg AUTH0_AUDIENCE=${{ secrets.AUTH0_AUDIENCE }}
          --build-arg GRAPHQL_ENDPOINT=${{ secrets.GRAPHQL_ENDPOINT }}

      - name: login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: push image
        run: docker push ghcr.io/h-orito/${{ env.IMAGE_NAME }}

  deploy:
    needs: build
    runs-on: [self-hosted, k8s]
    steps:
      - name: release
        run: kubectl rollout restart deployment/chat-role-play-frontend
