name: delivery backend

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "backend/**"

jobs:
  delivery:
    runs-on: [self-hosted]
    steps:
      - name: clone repository
        uses: actions/checkout@v4

      - name: build
        run: |
          cd backend
          docker build -t ghcr.io/h-orito/chat-role-play-backend .
      - name: deploy
        env:
          PACKAGE_PAT: ${{ secrets.PACKAGE_PAT }}
        run: |
          echo "$PACKAGE_PAT" | docker login ghcr.io -u h-orito --password-stdin
          docker push ghcr.io/h-orito/chat-role-play-backend
      - name: release
        run: |
          kubectl delete pod -l app=chat-role-play-backend
