name: delivery backend

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "backend/**"

jobs:
  delivery:
    runs-on: [self-hosted]
    permissions:
      contents: read
      packages: write
    steps:
      - name: clone repository
        uses: actions/checkout@v4

      - name: build
        run: |
          cd backend
          docker build -t ghcr.io/h-orito/chat-role-play-backend .
      - name: deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ACTOR: ${{ github.actor }}
        run: |
          echo "$GITHUB_TOKEN" | docker login ghcr.io -u "$ACTOR" --password-stdin
          docker push ghcr.io/h-orito/chat-role-play-backend
      - name: release
        run: |
          kubectl delete pod -l app=chat-role-play-backend
