name: delivery frontend

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  delivery:
    runs-on: [self-hosted]
    env:
      IMAGE_NAME: chat-role-play-frontend
    steps:
      - name: clone repository
        uses: actions/checkout@v2

      - name: build
        run: >
          docker build
          -t ghcr.io/h-orito/${{ env.IMAGE_NAME }}:latest .
          --build-arg AUTH0_DOMAIN=${{ secrets.AUTH0_DOMAIN }}
          --build-arg AUTH0_CLIENT_ID=${{ secrets.AUTH0_CLIENT_ID }}
          --build-arg AUTH0_AUDIENCE=${{ secrets.AUTH0_AUDIENCE }}
          --build-arg GRAPHQL_ENDPOINT=${{ secrets.GRAPHQL_ENDPOINT }} ./frontend
      - name: deploy
        run: |
          docker login ghcr.io -u h-orito -p ${{ secrets.PACKAGE_PAT }}
          docker push ghcr.io/h-orito/${{ env.IMAGE_NAME }}
      - name: release
        run: |
          kubectl delete pod -l app=chat-role-play-frontend
